name: Tinfoil
description: Make players perform commands.
author: StarTux
version: 0.1
api-version: '1.21'
main: com.winthier.tinfoil.TinfoilPlugin
depend: []
commands:
  tinfoil:
    description: Make a player perform a command.
    usage: /tinfoil <player> <command...>
    permission: tinfoil.tinfoil
permissions:
  tinfoil.tinfoil:
    description: Use the "/tinfoil" command.
    default: op
